[package]
name = "rust_csv_processing"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
rustfmt = "0.10.0"
serde = { version = "1.0.206", features = ["derive"] }
serde_json = "1.0.122"
